### ISSUE TITLE
[t-date-range-picker ]  使用v-model绑定 ref 后就，更新ref报错，但功能正常

### ISSUE THREAD

**Issue by nefulan** [Tencent/tdesign-vue-next#1564]
### tdesign-vue-next 版本

0.17.4

### 重现链接

请款步骤

### 重现步骤

<template>
  <t-select id="select-case" :v-model="checkCase" placeholder="请选择" multiple>
    <t-option v-for="item in caseOptions" :key="item.value" :label="item.label" :value="item.value"> </t-option>
  </t-select>
</template>

<script lang="ts">
export default {
  name: 'Test',
};
</script>
<script setup lang="ts">
import { ref } from 'vue';

const checkCase = ref(null);
const caseOptions = ref([
  { label: 'name1', value: '1' },
  { label: 'name2', value: '2' },
]);
</script>
点击下拉选项，报错
useInputWidth.ts:8 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')
    at updateInputWidth2 (useInputWidth.ts:8:20)
    at useInputWidth.ts:15:9

### 期望结果

不报错

### 实际结果

报错

### 框架版本

^3.2.31

### 浏览器版本

104.0.5112.101 (正式版本) (x86_64) 

### 系统版本

macOS 版本11.3.1（版号20E241）

### Node版本

v18.4.0

**Comment by HQ-Lin** [comment]
提供一个在线链接我看看？
<img width="469" alt="image" src="https://user-images.githubusercontent.com/24469546/188600084-967d185b-acd4-4651-b6d7-bc31201af9c8.png">
