### ISSUE TITLE
[t-upload] t-upload无法上传图片（没有提供完整的可复现问题代码或链接，无法处理）

### ISSUE THREAD

**Issue by ronleeon** [Tencent/tdesign-vue-next#2119]
### tdesign-vue-next 版本

0.25.0

### 重现步骤

按照官方实例上传图片，无法上传，
代码实例：
```js
<t-upload
        ref="uploadRef1"
        v-model="file1"
        action="https://service-bv448zsw-1257786608.gz.apigw.tencentcs.com/api/upload-demo"
        theme="image"
        tips="单张图片文件上传（上传成功状态演示）"
        accept="image/*"
        :disabled="false"
        :auto-upload="true"
        multiple
        :upload-all-files-in-one-request="true"
        :locale="{
          triggerUploadText: {
            image: '请选择图片',
          },
        }"
        @fail="handleFail"
      ></t-upload>
```

### 期望结果

成功上传不报错

### 实际结果

控制台报错：
```

main.ts:304 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'find')
    at main.ts:304:40
    at Array.filter (<anonymous>)
    at main.ts:303:26
    at new Promise (<anonymous>)
    at validateFile (main.ts:301:10)
    at onFileChange2 (useUpload.ts:154:18)
    at onNormalFileChange2 (useUpload.ts:204:21)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at HTMLInputElement.invoker (runtime-dom.esm-bundler.js:345:9)
```
是这段代码抱报上错误
```js
export function validateFile(
  params: FileChangeParams
): Promise<FileChangeReturn> {
  const { files, uploadValue, max, allowUploadDuplicateFile } = params;
  return new Promise((resolve) => {
    // 是否允许相同的文件名存在
    let tmpFiles = files.filter((file) => {
      const sameNameFile = uploadValue.find((t) => t.name === file.name);
      return allowUploadDuplicateFile || !sameNameFile;
    });

    let hasSameNameFile = false;
    if (tmpFiles.length < files.length) {
      hasSameNameFile = true;
    }
    if (!tmpFiles.length) {
      const tFiles = formatToUploadFile(files, params.format, params.autoUpload);
      resolve({ hasSameNameFile, file: tFiles?.[0], files: tFiles, validateResult: { type: 'FILTER_FILE_SAME_NAME' } });
      return;
    }

```

### 框架版本

Vue(3.2.38)

### 浏览器版本

Chrom(108.0.5359.94)

### 系统版本

5.15.78-1-MANJARO 

### Node版本

v18.7.0

**Comment by chaishi** [comment]
uploadValue.find 报错，说明 `uploadValue` 为空，也就是 Upload 组件的 `value` 为空，请务必传入合法的 `value`，必须是一个数组 `[]`

<img width="814" alt="image" src="https://user-images.githubusercontent.com/11605702/206872624-521f8a10-4e0f-477f-8d7d-3175bceaedd4.png">

**Comment by chaishi** [comment]
如果还有其他的问题，可以单独再开 issue
如果这个问题还有疑问，可以 reopen 这个 issue
