### ISSUE TITLE
[Nuxt3] 相关问题收集

### ISSUE THREAD

**Issue by PengYYYYY** [Tencent/tdesign-vue-next#2191]
### 这个功能解决了什么问题

nuxt3 问题收集

### 你建议的方案是什么

nuxt3 问题收集

**Comment by yixiaco** [comment]
t-tooltip 在nuxt3报错 window is not defined，版本tdesign: 1.0.6，nuxt3:3.2.0

**Comment by yixiaco** [comment]
t-pagination 在nuxt3报错 navigator is not defined，版本tdesign: 1.0.6，nuxt3:3.2.0
<details>
<summary>报错详情</summary>

```typescript
    at ReactiveEffect.fn (\node_modules\tdesign-vue-next\es\pagination\usePaginationClasses.mjs:104:224)
    at ReactiveEffect.run (\node_modules\@vue\reactivity\dist\reactivity.cjs.js:173:25)
    at ComputedRefImpl.get value [as value] (\node_modules\@vue\reactivity\dist\reactivity.cjs.js:1163:39)
    at Proxy. (\node_modules\tdesign-vue-next\es\pagination\pagination.mjs:602:44)
    at renderComponentRoot (\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:906:44)
    at renderComponentSubTree (\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:719:51)
    at renderComponentVNode (\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:644:16)
    at Module.ssrRenderComponent (\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:94:12)
```
</details>
