### ISSUE TITLE
[组件名称]tdesign-vue-next 从1.0.0 升级成1.0.8后，对t-table的data属性动态赋值出现错误

### ISSUE THREAD

**Issue by TonyLuo** [Tencent/tdesign-vue-next#2426]
### tdesign-vue-next 版本

1.0.8

### 重现步骤

tdesign-vue-next 从1.0.0 升级成1.0.8后，对t-table的data属性动态赋值出现错误

### 实际结果

```
TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
    at addObserver2 (useResizeObserver.ts:22:23)
    at watch.immediate (useResizeObserver.ts:30:15)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at Array.job (runtime-core.esm-bundler.js:1794:17)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:343:32)
    at flushJobs (runtime-core.esm-bundler.js:397:9)
    at flushJobs (runtime-core.esm-bundler.js:403:13)



addObserver2 | @ | useResizeObserver.ts:22
-- | -- | --
  | watch.immediate | @ | useResizeObserver.ts:30
  | callWithErrorHandling | @ | runtime-core.esm-bundler.js:157
  | callWithAsyncErrorHandling | @ | runtime-core.esm-bundler.js:166
  | job | @ | runtime-core.esm-bundler.js:1794
  | flushPostFlushCbs | @ | runtime-core.esm-bundler.js:343
  | flushJobs | @ | runtime-core.esm-bundler.js:397
  | flushJobs | @ | runtime-core.esm-bundler.js:403
  | Promise.then (async) |   |  
  | nextTick | @ | runtime-core.esm-bundler.js:244
  | watch.immediate | @ | useInputWidth.ts:24
  | callWithErrorHandling | @ | runtime-core.esm-bundler.js:157
  | callWithAsyncErrorHandling | @ | runtime-core.esm-bundler.js:166
  | job | @ | runtime-core.esm-bundler.js:1794
  | doWatch | @ | runtime-core.esm-bundler.js:1837
  | watch | @ | runtime-core.esm-bundler.js:1671
  | addListeners2 | @ | useInputWidth.ts:20
  | (anonymous) | @ | useInputWidth.ts:35
  | (anonymous) | @ | runtime-core.esm-bundler.js:2739
  | callWithErrorHandling | @ | runtime-core.esm-bundler.js:157
  | callWithAsyncErrorHandling | @ | runtime-core.esm-bundler.js:166
  | hook.__weh.hook.__weh | @ | runtime-core.esm-bundler.js:2713
  | flushPostFlushCbs | @ | runtime-core.esm-bundler.js:343
  | flushJobs | @ | runtime-core.esm-bundler.js:397
  | Promise.then (async) |   |  
  | queueFlush | @ | runtime-core.esm-bundler.js:282
  | queuePostFlushCb | @ | runtime-core.esm-bundler.js:304
  | queueEffectWithSuspense | @ | runtime-core.esm-bundler.js:1585
  | scheduler | @ | runtime-core.esm-bundler.js:1820
  | triggerEffect | @ | reactivity.esm-bundler.js:397
  | triggerEffects | @ | reactivity.esm-bundler.js:387
  | triggerRefValue | @ | reactivity.esm-bundler.js:1003
  | (anonymous) | @ | reactivity.esm-bundler.js:1137
  | triggerEffect | @ | reactivity.esm-bundler.js:397
  | triggerEffects | @ | reactivity.esm-bundler.js:382
  | triggerRefValue | @ | reactivity.esm-bundler.js:1003
  | (anonymous) | @ | reactivity.esm-bundler.js:1137
  | triggerEffect | @ | reactivity.esm-bundler.js:397
  | triggerEffects | @ | reactivity.esm-bundler.js:382
  | triggerRefValue | @ | reactivity.esm-bundler.js:1003
  | set value | @ | reactivity.esm-bundler.js:1048
  | finalizeNavigation | @ | vue-router.mjs:3334
  | (anonymous) | @ | vue-router.mjs:3207
  | Promise.then (async) |   |  
  | pushWithRedirect | @ | vue-router.mjs:3174
  | (anonymous) | @ | vue-router.mjs:3190
  | Promise.then (async) |   |  
  | pushWithRedirect | @ | vue-router.mjs:3174
  | push | @ | vue-router.mjs:3099
  | install | @ | vue-router.mjs:3530
  | use | @ | runtime-core.esm-bundler.js:4381
  | (anonymous) | @ | main.ts:15


```

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-xz2kfq?file=package.json,src%2Fdemo.vue

我在这个链接里面尝试了一下动态赋值，表现正常。没有复现 @TonyLuo 提到的问题

请再次确认自己最终安装的版本号是否真的为 `1.0.8`

**Comment by chaishi** [comment]
由于无法复现问题，且没有提供可以复现问题的链接、场景、背景等信息，进而无法处理问题。issue 暂时关闭。

待提供可复现问题的更多信息后，可以再 reopen 当前 issue
