### ISSUE TITLE
[Bug] 库引入报错

### ISSUE THREAD

**Issue by sufuwang** [Tencent/tdesign-vue-next#256]
### 我的环境如下
    1. vitePress 中
 tdesign-vue-next@^0.6.0:
  version "0.6.4"
  resolved "https://mirrors.tencent.com/npm/tdesign-vue-next/-/tdesign-vue-next-0.6.4.tgz#4d2c241cf79e4932b3076886a13962665e588138"
  integrity sha512-F5cJVBcGvtyf9LFXHeS2SnkQAEVOFNpHwojXMUZdYREhW3dP5TyWX5rhDWMPi/ajPlzBCFvAD5Nd32nLCKvmuA==
  dependencies:
    "@babel/runtime" "^7.14.8"
    "@popperjs/core" "^2.9.3"
    "@types/lodash" "^4.14.175"
    "@types/validator" "^13.6.3"
    dayjs "^1.9.7"
    less "^4.1.2"
    lodash "^4.17.15"
    tdesign-icons-vue-next "~0.0.5"
    validator "^13.5.1"

2. nuxt 中

tdesign-vue-next@^0.7.0:
  version "0.7.0"
  resolved "https://mirrors.tencent.com/npm/tdesign-vue-next/-/tdesign-vue-next-0.7.0.tgz#d15ede340e8892cc6556fbb89fbcf80e0c35fc83"
  integrity sha512-t8Efh4IfJomx2lxwDNMFOXgHWecR4gzdvfNXFQ+YbIykwOj+N3Vq8EHaD8CASI4dJG08RQaUkSj3RRyy7/efHg==
  dependencies:
    "@babel/runtime" "^7.14.8"
    "@popperjs/core" "^2.9.3"
    "@types/lodash" "^4.14.175"
    "@types/validator" "^13.6.3"
    dayjs "^1.9.7"
    less "^4.1.2"
    lodash "^4.17.15"
    tdesign-icons-vue-next "~0.0.6"
    validator "^13.5.1"

### 问题复现步骤是：

    在 vitePress 和 nuxt 项目中报错

    1. vitePress
上午11:02:23 [vite] Internal server error: Failed to resolve import "./chunk-62H3E4UC.js" from "node_modules/.vite/tdesign-vue-next.js?v=0af01df1". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/sufuwang/···/node_modules/.vite/tdesign-vue-next.js?v=0af01df1
  27 |    watchEffect,
  28 |    withDirectives
  29 |  } from "./chunk-62H3E4UC.js";
     |          ^
  30 |  
  31 |  // node_modules/lodash/_freeGlobal.js
      at formatError (/Users/sufuwang/···/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36769:46)
      at TransformContext.error (/Users/sufuwang/···/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36765:19)
      at normalizeUrl (/Users/sufuwang/···/node_modules/vite/dist/node/chunks/dep-f5552faa.js:73703:26)
      at async TransformContext.transform (/Users/sufuwang/···/node_modules/vite/dist/node/chunks/dep-f5552faa.js:73843:57)
      at async Object.transform (/Users/sufuwang/···/node_modules/vite/dist/node/chunks/dep-f5552faa.js:36985:30)
      at async doTransform (/Users/sufuwang/···/node_modules/vite/dist/node/chunks/dep-f5552faa.js:52060:29)

    2. nuxt
 
(node:41086) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/sufuwang/···/node_modules/tdesign-vue-next/es/utils/clipboard.js:7
import { c as commonjsGlobal, g as getDefaultExportFromCjs } from '../_chunks/dep-31e2e0ac.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)

**Comment by sufuwang** [comment]
vitePress 重启可以解决

**Comment by sufuwang** [comment]
Nuxt: 
tdesign 的 package.json 中添加 type: module ，又报
```js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/sufuwang/···/node_modules/lodash/isObject' imported from /Users/sufuwang/Downloads/Code/Github/system.sufu.site/node_modules/tdesign-vue-next/es/index.js
Did you mean to import lodash/isObject.js?
```
解决完 tdesign-vue-next/es/index.js 的后缀之后，又报这个
```js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/sufuwang/···/node_modules/lodash/isString' imported from /Users/sufuwang/···/node_modules/tdesign-vue-next/es/button/index.js
```

**Comment by waset** [comment]
[nuxt3 的复现](https://github.com/waset/TD-test.git)

**Comment by pengYYYYY** [comment]
我这边在做一些尝试，目前在解决一些winodws对象之类的兼容性问题，等待一下。

**Comment by waset** [comment]
可以参考一下 [nuxt3](https://v3.nuxtjs.org/guide/going-further/esm) 的新文档

**Comment by pengYYYYY** [comment]
0.15.0 已修复
