### ISSUE TITLE
[ColorPicker] 在form-item中使用color-picker，切换组件的显示隐藏，页面报错

### ISSUE THREAD

**Issue by colaiven** [Tencent/tdesign-vue-next#2895]
### tdesign-vue-next 版本

1.3.4

### 重现链接

https://stackblitz.com/edit/vwk5yj-l5hvex?file=src%2Fdemo.vue

### 重现步骤

在form-item中使用color-picker，切换组件的显示隐藏，页面就报错了，报错信息如下：

Uncaught runtime errors:
×
ERROR
ResizeObserver loop limit exceeded
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:271:7)
![image](https://github.com/Tencent/tdesign-vue/assets/46585176/2b9ef226-7492-4b70-ad6b-2a2300643d98)

单独使用color-picker  或者改用v-if不存在这个问题，另外这个问题貌似只存在用webpack打包的方式，用vite没有复现这个bug

**Comment by colaiven** [comment]
有大佬认领吗？有点急，影响比较大

**Comment by uyarn** [comment]
我来看看

**Comment by RSS1102** [comment]
https://github.com/user-attachments/assets/72c42f11-c1f6-4d04-9002-35ac9811f73b
