### ISSUE TITLE
[Bug] nuxt3

### ISSUE THREAD

**Issue by waset** [Tencent/tdesign-vue-next#314]
期望支持[nuxt3](https://v3.nuxtjs.org/),目前引入报错

**Comment by waset** [comment]
<img width="1679" alt="企业微信截图_ac9b8987-cb7c-4791-9cac-1afba3397fd1" src="https://user-images.githubusercontent.com/55943270/153976656-17a566f3-d665-4bd1-b15e-9d163f7c2ffb.png">

**Comment by waset** [comment]
(node:6469) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Volumes/www/vue/nuxt3-app/node_modules/tdesign-vue-next/es/utils/clipboard.js:7
import { c as commonjsGlobal, g as getDefaultExportFromCjs } from '../_chunks/dep-b66bfe36.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1032:15)
    at Module._compile (node:internal/modules/cjs/loader:1067:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
[vite dev] Error loading external "/Volumes/www/vue/nuxt3-app/node_modules/tdesign-vue-next/es/utils/clipboard.js".
  at file://./.nuxt/dist/server/server.mjs:40233:291  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:98195:3)
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:206:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)

**Comment by vnues** [comment]
看起来是项目不支持es module

**Comment by waset** [comment]
重复贴，转 #256
