### ISSUE TITLE
[Build] npm run build 时报错

### ISSUE THREAD

**Issue by insub** [Tencent/tdesign-vue-next#3204]
### tdesign-vue-next 版本

1.4.2

### 重现步骤

npm run build

### 实际结果

[!] Error: Could not resolve './style/css.mjs' from src/affix/style/index.js
Error: Could not resolve './style/css.mjs' from src/affix/style/index.js
    at error (D:\Sites\tdesign-vue-next-develop\node_modules\rollup\dist\shared\rollup.js:198:30)
    at ModuleLoader.handleResolveId (D:\Sites\tdesign-vue-next-develop\node_modules\rollup\dist\shared\rollup.js:22287:24)
    at D:\Sites\tdesign-vue-next-develop\node_modules\rollup\dist\shared\rollup.js:22250:26

**Comment by uyarn** [comment]
ignore import这个插件 在windows的环境不太兼容 暂时不支持build 还在处理中

**Comment by AuYuHui** [comment]
win 可以安装个 wsl
