### ISSUE TITLE
[DatePicker] 选中后报错

### ISSUE THREAD

**Issue by Joycezhangw** [Tencent/tdesign-vue-next#3493]
### tdesign-vue-next 版本

1.6.2

### 重现链接

https://codepen.io/Joycezhangw/pen/BavXozZ

### 重现步骤

日期选择器报错如下
`
runtime-core.esm-bundler.js:221 Uncaught TypeError: Cannot read properties of undefined (reading 'focus')
    at Proxy.onOverlayClick2 (select-input.tsx:90:24)
    at onOverlayClick (popup.tsx:381:7)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1
`

### 框架版本

Vue(3.3.4)

### Node版本

18

### 补充说明

![image](https://github.com/Tencent/tdesign-vue-next/assets/18376965/b8644731-f7ad-415d-9f97-ee58f7efc0c4)

**Comment by uyarn** [comment]
fixed in 1.6.5

**Comment by xiaosansiji** [comment]
@Joycezhangw 连接里的例子未见到报错，需要你补充下代码或者增加下操作描述
