### ISSUE TITLE
[Table] 编辑单元格无效

### ISSUE THREAD

**Issue by wflashy** [Tencent/tdesign-vue-next#3563]
### tdesign-vue-next 版本

是

### 重现步骤

请直接看【示例】

https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC

控制台提示错误：
index.34f600c4.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at _ (index.34f600c4.js:49:48162)
    at Or.cell (index.34f600c4.js:49:52641)
    at pf (index.34f600c4.js:44:56302)
    at H (index.34f600c4.js:44:58735)
    at index.34f600c4.js:44:59709
    at Array.map (<anonymous>)
    at Proxy.<anonymous> (index.34f600c4.js:44:59419)
    at Dx (index.34f600c4.js:1:17090)
    at gy.Pt [as fn] (index.34f600c4.js:1:41406)
    at gy.run (index.34f600c4.js:1:5218)
irt @ index.34f600c4.js:1

**Comment by chaishi** [comment]
描述内容过少，无法处理

**Comment by SadWood** [comment]
> ### tdesign-vue-next 版本
> 是
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> 请直接看【示例】
> 
> https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC
> 
> 控制台提示错误： index.34f600c4.js:1 TypeError: Cannot read properties of undefined (reading 'includes') at _ (index.34f600c4.js:49:48162) at Or.cell (index.34f600c4.js:49:52641) at pf (index.34f600c4.js:44:56302) at H (index.34f600c4.js:44:58735) at index.34f600c4.js:44:59709 at Array.map () at Proxy. (index.34f600c4.js:44:59419) at Dx (index.34f600c4.js:1:17090) at gy.Pt [as fn] (index.34f600c4.js:1:41406) at gy.run (index.34f600c4.js:1:5218) irt @ index.34f600c4.js:1
> 
> ### 期望结果
> _No response_
> 
> ### 实际结果
> _No response_
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> _No response_

有解决方案了吗？之前正常的单元格编辑功能在新版本出现了相同的报错问题

**Comment by SadWood** [comment]
> 描述内容过少，无法处理

在“可编辑单元格的表格”的示例中，申请人列，任意一个单元格中，输入任意字符，均可复现报错问题
