### ISSUE TITLE
submenu   自动导入失败

### ISSUE THREAD

**Issue by oldlwhite** [Tencent/tdesign-vue-next#368]
### 重现链接
https://tdesign.tencent.com/vue-next/components/menu

### 重现步骤
把官网的例子替换一下就ok了

### 期望结果
替换例子不报错

### 实际结果
替换例子会报错
t-submenu 只有这个组件导入报错，其他组件不报错

### 补充说明
[plugin:vite:import-analysis] Failed to resolve import "tdesign-vue-next/es/submenu/style" from "src/components/admin/main.vue". Does the file exist?
/root/SpiderAdmin/src/components/admin/main.vue:1:156
1  |  import { resolveComponent } from 'vue';/* unplugin-vue-components disabled */import { Submenu as __unplugin_components_3 } from 'tdesign-vue-next';import 'tdesign-vue-next/es/submenu/style';
   |                                                                                                                                                             ^
2  |  import { Icon as __unplugin_components_2 } from 'tdesign-vue-next';
3  |  import { Menu as __unplugin_components_1 } from 'tdesign-vue-next';import 'tdesign-vue-next/es/menu/style';
    at formatError (/root/SpiderAdmin/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38082:46)
    at TransformContext.error (/root/SpiderAdmin/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38078:19)
    at normalizeUrl (/root/SpiderAdmin/node_modules/vite/dist/node/chunks/dep-971d9e33.js:69803:26)
    at async TransformContext.transform (/root/SpiderAdmin/node_modules/vite/dist/node/chunks/dep-971d9e33.js:69943:57)
    at async Object.transform (/root/SpiderAdmin/node_modules/vite/dist/node/chunks/dep-971d9e33.js:38318:30)
    at async doTransform (/root/SpiderAdmin/node_modules/vite/dist/node/chunks/dep-971d9e33.js:53014:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

| Environment | Info |
|---|---|
| 相关版本 | 0.9.1 |
| 框架版本 / 基础库版本 | vue(3.2.25)  / unplugin-vue-components(0.17.20) |
| 系统、浏览器 | chrome |
| Node版本 | v17.5.0 |

**Comment by LeeJim** [comment]
这个问题已经修复了，https://github.com/antfu/unplugin-vue-components/pull/321
等 unplugin-vue-components 发布 0.17.22 版本
